### ISSUE TITLE
Counts tellers as voters

### ISSUE THREAD

**Issue by dracos** [puntofisso/CommonsViz#1]
e.g. Universal credit roll out (I can't provide a direct link as the site doesn't change the URL when an option is picked) was 299-0, not 301-2, see https://www.theyworkforyou.com/debates/?id=2017-10-18a.953.0

**Comment by puntofisso** [comment]
Thanks for the comment, good point about tellers! I'll amend the count and potentially use a different "pot" to put their placeholder (or some other graphical feature).
