### ISSUE TITLE
Dropdown confusing

### ISSUE THREAD

**Issue by dracos** [puntofisso/CommonsViz#2]
Multiple entries with the same title, only an ID telling them apart. PublicWhip has manually edited titles/descriptions, for example the three European Union (Withdrawal) Bill divisions are:
"European Union (Withdrawal) Bill — Decline Second Reading" http://www.publicwhip.org.uk/division.php?date=2017-09-11&number=13
"European Union (Withdrawal) Bill — Second Reading" http://www.publicwhip.org.uk/division.php?date=2017-09-11&number=14
"European Union (Withdrawal) Bill — Programme" http://www.publicwhip.org.uk/division.php?date=2017-09-11&number=15

**Comment by puntofisso** [comment]
I'll look into embedding this, but the goal of this project in reality is to use it as a prop for PDS to publish the data comprehensively. For example, to an uniformed eye there is an obvious discrepancy in what you get from https://hansard.parliament.uk/search/Divisions?startDate=2017-06-08&searchTerm=finance%20bill&house=Commons&includeCommitteeDivisions=True
versus what you get from http://hansard.services.digiminster.com/Divisions/list.json?startdate=2017-06-08
I've been engaging with PDS about this, so I hope to get to a stage where the data is clean enough.

**Comment by dracos** [comment]
Yes, I find the parliament.uk XML pages such as http://api.data.parliament.uk/resources/files/783133.xml (there's an Atom feed, but I don't know how you can gain a fuller list) more up-to-date and comprehensive. None missing there I can see.
